name: Build and Deploy

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: Install dioxus-cli
        run: cargo install dioxus-cli

      - name: Build
        run: dx build --release
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: dist/
      
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: dist
