name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: Install dioxus-cli
        run: cargo install dioxus-cli

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install tailwindcss
        working-directory: ./css
        run: |
          pnpm install
          pnpm tailwindcss -i ./tailwind.input.css -o ../assets/tailwind.css --minify

      - name: Build
        run: dx build --release

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/dx/nord-wg-gen/release/web/public
