name: Build and Deploy

on: push

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: Install dioxus-cli
        run: cargo install dioxus-cli

      - uses: oven-sh/setup-bun@v1
        working-directory: ./css
        run: |
          bun install
          bun tailwindcss -i ./tailwind.input.css -o ../assets/tailwind.css

      - name: Build
        run: dx build --release

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
